### ISSUE TITLE
donate project to Nebula-Contrib community

### ISSUE THREAD

**Issue by wey-gu** [hjfruit/testcontainers-nebula#2]
Could we invite this amazing impl. on NeublaGraph for testcontainers to be yet another project under Nebula-Contrib?

**Comment by jxnu-liguobin** [comment]
> Could we invite this amazing impl. on NeublaGraph for testcontainers to be yet another project under Nebula-Contrib?

I think so, it can let more people know about it

**Comment by wey-gu** [comment]
Great!!

Let's do so! @Shinji-IkariG @QingZ11

**Comment by wey-gu** [comment]
done!🎉

**Comment by QingZ11** [comment]
@jxnu-liguobin Thank you again ❤️
